server:
  port: 8100
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./app;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
